In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from xgboost import XGBClassifier
import pickle

In [2]:
df = pd.read_csv("C://Users//admin//Desktop//Thyriod Detection//Data_Preprocessing//raw_data.csv")
df.head()

,TT4,FTI,sex,on_thyroxine,T3,query_hyperthyroid,psych,sick,tumor,pregnant,Class
0,125.0,109.000000,0,0,2.500000,0,0,0,0,0,0
1,109.0,120.000000,1,0,2.013609,0,0,0,0,0,0
2,175.0,110.486326,0,1,1.900000,0,0,0,0,0,0
3,61.0,70.000000,0,0,1.200000,0,0,0,0,0,0
4,183.0,141.000000,0,1,2.013609,0,0,0,0,0,0

In [6]:
x = df.drop('Class' , axis = 1)
y = df.Class

from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.10 , random_state = 120)

#x = x.values
#y = y.values

x_train = x_train.values
y_train = y_train.values

In [7]:
xgb = XGBClassifier()
xgb.fit(x_train , y_train)
#xgb.score(x_test , y_test)
pickle.dump(xgb, open('model.pkl' , 'wb'))
model=pickle.load(open('model.pkl' , 'rb'))